### ISSUE TITLE
ZCL_DISPATCHER->_GET_MAPPED_RESOURCE trying to set private attributes in ZCL_RESOURCE instance

### ISSUE THREAD

**Issue by binho09** [rvanmil/ABAP-OOP-Library#4]
046 CREATE OBJECT resource TYPE (resource_record-class).
047 resource->_name = resource_record-name.
048 resource->_path = resource_record-path.
049 resource->_id = resource_id.

**Comment by rvanmil** [comment]
This is possible because ZCL_RESOURCE has a friend definition for ZCL_DISPATCHER.

Thanks :)

**Comment by binho09** [comment]
Thank you, René! For the great job done with this library!

**Comment by rvanmil** [comment]
You're welcome! Thanks for reporting issues! 👍
